import type { ContentBlock } from "../types"

export const algorithmesSpatiauxFiche: ContentBlock[] = [
  {
    type: "table",
    headers: ["Algorithme / structure", "Ce qu'il fait", "Complexité (cas moyen)"],
    rows: [
      ["Plus proche voisin (naïf)", "Compare la distance à chaque candidat, garde le minimum", "O(n)"],
      ["IDW (pondération inverse à la distance)", "Moyenne pondérée par 1/dᵖ des valeurs connues", "O(n) par point interpolé"],
      ["Enveloppe convexe (convex hull)", "Plus petit polygone convexe contenant tous les points", "O(n log n)"],
      ["Douglas-Peucker", "Simplifie une ligne selon la distance perpendiculaire au segment", "O(n log n) moyen, O(n²) pire cas"],
      ["Visvalingam-Whyatt", "Simplifie une ligne selon l'aire du triangle local", "O(n log n) avec file de priorité"],
      ["Test du rayon (ray casting)", "Point dans un polygone : parité des traversées du bord", "O(nombre de sommets du polygone)"],
      ["Grille régulière", "Découpe l'espace en cellules de taille fixe", "O(1) moyen si densité homogène"],
      ["Quadtree", "Subdivise récursivement en 4 quadrants selon la densité", "O(log n) moyen"],
      ["k-d tree", "Arbre binaire, alterne les axes à la médiane", "O(log n) moyen (plus proche voisin)"],
      ["R-tree (→ GiST/PostGIS)", "Rectangles englobants imbriqués pour géométries étendues", "O(log n) moyen"],
      ["Triangulation de Delaunay", "Triangule en maximisant le plus petit angle (critère du cercle circonscrit)", "O(n log n)"],
      ["Diagramme de Voronoï/Thiessen", "Dual de Delaunay : zone la plus proche de chaque point", "O(n log n)"],
      ["TIN", "Interpolation barycentrique exacte à l'intérieur de chaque triangle de Delaunay", "—"],
      ["Spline", "Surface lisse minimisant la courbure, peut dépasser le min/max (overshoot)", "—"],
      ["Krigeage (→ Le Compas)", "Pondération dérivée du variogramme, + variance d'incertitude", "—"],
      ["Dijkstra / A* (→ Le Compas)", "Plus court chemin depuis une source unique, poids positifs", "O((V+E) log V)"],
      ["Bellman-Ford", "Plus court chemin, poids négatifs autorisés, détecte les cycles négatifs", "O(V·E)"],
      ["Floyd-Warshall", "Plus court chemin entre toutes les paires de nœuds", "O(V³)"],
      ["DBSCAN", "Clustering par densité (eps, minPts), détecte le bruit, k non fixé", "O(n log n) avec index"],
      ["OPTICS", "Généralise DBSCAN à des densités variables (reachability plot)", "O(n log n) avec index"],
      ["SKATER / AZP", "Régionalisation : clusters statistiquement homogènes ET contigus", "—"],
      ["TSP (Held-Karp exact / 2-opt / Christofides)", "Cycle de coût minimal visitant tous les nœuds une fois", "O(n²·2ⁿ) exact ; heuristiques polynomiales"],
      ["VRP (Clarke-Wright)", "Généralise le TSP à plusieurs véhicules à capacité limitée", "—"],
      ["Centralité d'intermédiarité (betweenness)", "Part des plus courts chemins passant par un nœud", "—"],
      ["Centralité de proximité (closeness)", "Inverse de la distance moyenne à tous les autres nœuds", "—"],
      ["Clark-Evans", "Indice R : semis agrégé (R<1), aléatoire (R=1) ou régulier (R>1)", "—"],
      ["Fonction K de Ripley (→ Les Statistiques)", "Agrégation/dispersion testée à toutes les échelles de distance", "—"],
      ["Enveloppe de simulation Monte Carlo", "Teste la significativité par comparaison à N semis simulés sous CSR", "—"],
      ["Co-localisation (indice de participation PI)", "Détecte quelles catégories de points s'associent spatialement", "—"],
    ],
  },
  {
    type: "formula",
    label: "IDW généralisée",
    formula: "Z(P) = [ Σᵢ zᵢ / dᵢᵖ ] / [ Σᵢ 1 / dᵢᵖ ]",
    note: "p=1 : décroissance douce ; p=2 : standard ; p élevé : proche du plus proche voisin pur.",
  },
  {
    type: "formula",
    label: "Clark-Evans",
    formula: "R = r̄A / r̄E,  avec r̄E = 1 / (2√(n/A))",
  },
  {
    type: "comparison",
    items: [
      { label: "DBSCAN", points: ["k émerge des données", "Détecte le bruit", "Formes de cluster quelconques"] },
      { label: "k-means (Du Hasard et de la Preuve)", points: ["k fixé à l'avance", "Aucune notion de bruit", "Suppose des clusters ronds/compacts"] },
    ],
  },
  {
    type: "callout",
    tone: "warning",
    title: "À ne pas confondre",
    text: "Delaunay relie des points par des triangles ; Voronoï découpe l'espace en zones — les deux sont duaux mais ne répondent pas à la même question. Clip (couvert dans QGIS) et Intersection ne gardent pas les mêmes attributs. Un O(n²) reste instantané sur quelques centaines de points ; l'écart avec un O(n log n) n'explose qu'à partir de plusieurs millions de points.",
  },
  {
    type: "callout",
    tone: "info",
    title: "Géométrie robuste",
    text: "Une géométrie auto-intersectante ou un test d'orientation instable (trois points presque alignés, arrondi flottant) peut fausser silencieusement un résultat — vérifier la validité (ST_IsValid / \"Vérifier la validité\" QGIS) avant tout traitement lourd, comme on vérifie un CRS avant un calcul de surface.",
  },
  {
    type: "callout",
    tone: "example",
    title: "Passage à l'échelle",
    text: "Au-delà de plusieurs dizaines de millions de géométries : simplification en flux (streaming), parallélisation (Apache Sedona), indexation hors mémoire (R-tree/quadtree sur disque, par blocs) et partitionnement spatial (tuilage) prennent le relais des structures classiques.",
  },
]
