import type { ContentBlock } from "../types"

export const analyseStatistiqueFiche: ContentBlock[] = [
  {
    type: "table",
    headers: ["Indicateur", "Formule / statistique clé", "À quoi ça sert"],
    rows: [
      ["Moyenne x̄", "Σxᵢ / n", "Tendance centrale, sensible aux valeurs extrêmes"],
      ["Médiane", "Valeur centrale de la série triée", "Tendance centrale, robuste aux valeurs extrêmes"],
      ["Écart-type σ", "√[ (1/n) Σ(xᵢ−x̄)² ]", "Dispersion autour de la moyenne"],
      ["Quartiles / EIQ", "Q1, médiane, Q3 ; EIQ = Q3−Q1", "Dispersion robuste, boîte à moustaches"],
      ["Loi normale", "Règle empirique 68-95-99,7 %", "Part des valeurs à 1σ / 2σ / 3σ de la moyenne"],
      ["Corrélation de Pearson r", "Σ(xᵢ−x̄)(yᵢ−ȳ) / [√Σ(xᵢ−x̄)² · √Σ(yᵢ−ȳ)²]", "Force et sens d'une relation linéaire, entre −1 et +1"],
      ["Erreur standard SE", "s / √n", "Variabilité d'échantillonnage d'une moyenne"],
      ["Intervalle de confiance 95 %", "x̄ ± t(0,025 ; n−1) · SE", "Fourchette plausible pour le paramètre de population"],
      ["t-test apparié", "t = d̄ / (s_d/√n)", "Comparer 2 mesures sur les mêmes individus"],
      ["t-test indépendant", "t = (x̄₁−x̄₂) / [sp·√(1/n₁+1/n₂)]", "Comparer les moyennes de 2 groupes distincts"],
      ["χ² (khi-deux)", "Σ (Oᵢ−Eᵢ)² / Eᵢ", "Indépendance ou ajustement, variables qualitatives"],
      ["ANOVA (F)", "F = CMB/CMW = [SSB/(k−1)] / [SSW/(N−k)]", "Comparer les moyennes de 3 groupes ou plus"],
      ["Régression simple", "ŷ = b₀+b₁x, b₁ = Σ(xᵢ−x̄)(yᵢ−ȳ)/Σ(xᵢ−x̄)²", "Prédire y à partir d'un seul x (moindres carrés)"],
      ["R²", "1 − SSrés/SStot", "Part de variance de y expliquée (= r² en régression simple)"],
      ["Régression multiple", "ŷ = β₀+β₁X₁+…+βₚXₚ", "Prédire y à partir de plusieurs X, coefficients « toutes choses égales »"],
      ["VIF", "VIFⱼ = 1/(1−Rⱼ²)", "Détecter la multicolinéarité (seuil usuel : 5 ou 10)"],
      ["Régression logistique", "ln(p/(1−p)) = β₀+β₁X₁+…", "Prédire une variable binaire (probabilité, log-odds)"],
      ["Odds ratio", "OR = e^βⱼ", "Effet multiplicatif sur la cote de l'événement"],
      ["ROC / AUC", "Aire sous la courbe (taux VP vs taux FP)", "Qualité d'un classifieur binaire, indépendamment du seuil"],
      ["ACP", "C·v = λ·v ; variance expliquée = λᵢ/Σλⱼ", "Réduire des variables numériques corrélées"],
      ["AFC / ACM", "Décomposition d'un tableau de contingence", "Équivalent de l'ACP pour des variables qualitatives"],
      ["k-means", "min Σₖ Σᵢ∈Ck ‖xᵢ−μₖ‖²", "Classer en k groupes fixés à l'avance"],
      ["CAH / Ward", "Fusions successives minimisant l'inertie intra", "Classer sans fixer k à l'avance (dendrogramme)"],
      ["Indice de Gini", "1 − Σ pᵢ²", "Critère de découpage d'un arbre de décision"],
      ["Forêt aléatoire", "Vote/moyenne sur de nombreux arbres bootstrappés", "Prédiction robuste + importance des variables"],
      ["Validation croisée k-fold", "CV = (1/k) Σ Erreurᵢ", "Estimer une erreur de généralisation honnête"],
      ["Biais-variance", "Erreur = Biais² + Variance + σ²", "Arbitrage entre sous- et sur-apprentissage"],
      ["Autocorrélation (ACF)", "rₖ = Σ(xₜ−x̄)(xₜ₊ₖ−x̄) / Σ(xₜ−x̄)²", "Dépendance d'une série temporelle à elle-même"],
      ["ARIMA(p,d,q)", "AR(p) + différenciation(d) + MA(q)", "Modéliser/prévoir une série temporelle"],
      ["Bootstrap", "Rééchantillonnage avec remise, B réplications", "IC empirique sans hypothèse de distribution"],
    ],
  },
  {
    type: "table",
    headers: ["Situation", "Test / méthode"],
    rows: [
      ["1 numérique, 2 groupes", "t-test (apparié ou indépendant)"],
      ["1 numérique, 3+ groupes", "ANOVA + post-hoc (Tukey)"],
      ["2 qualitatives", "χ² d'indépendance"],
      ["2 numériques, lien linéaire", "Pearson + régression simple"],
      ["1 numérique à prédire, plusieurs X numériques", "Régression multiple (VIF) ou forêt aléatoire"],
      ["1 binaire à prédire", "Régression logistique (ROC/AUC)"],
      ["Réduire beaucoup de variables numériques", "ACP"],
      ["Réduire beaucoup de variables qualitatives", "AFC / ACM"],
      ["Grouper sans étiquette", "k-means (k connu) ou CAH/Ward (k inconnu)"],
      ["Donnée datée, répétée dans le temps", "ACF, décomposition, ARIMA"],
    ],
  },
  {
    type: "comparison",
    items: [
      { label: "Erreur de type I", points: ["Rejeter H0 alors qu'elle est vraie", "Risque = α, fixé avant le test"] },
      { label: "Erreur de type II", points: ["Ne pas rejeter H0 alors qu'elle est fausse", "Risque = β, lié à la puissance (1−β)"] },
    ],
  },
  {
    type: "callout",
    tone: "warning",
    title: "Pièges classiques",
    text: "Corrélation n'est pas causalité (chercher un facteur de confusion). Une p-value non significative ne prouve pas l'absence d'effet — vérifier la puissance. R² = r² seulement en régression simple. Un VIF élevé signale une multicolinéarité, pas une erreur de calcul. Un F d'ANOVA significatif ne dit pas quels groupes diffèrent : test post-hoc nécessaire. Évaluer un modèle sur ses données d'entraînement surestime toujours sa performance réelle : toujours passer par une validation croisée.",
  },
  {
    type: "callout",
    tone: "info",
    title: "Cross-références",
    text: "Régression spatiale, autocorrélation spatiale (Moran, LISA, Gi*), MAUP : module Les Statistiques. Matrice de confusion, kappa, k-means sur pixels, biais-variance en deep learning : module L'Intelligence. Bootstrap et permutation en code R : module R. Décomposition tendance/saisonnalité/résidu appliquée au NDVI : module TerrSet (Earth Trends Modeler).",
  },
]
